name: Docker CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: DockerHub Login
      run: echo "$DOCKER_SECRET" | docker login -u frank15ortiz --password-stdin

    - name: Build & Push the Docker image
      run: |
       docker build . --file Dockerfile --tag royal-docker:$GITHUB_SHA --tag royal-docker:latest
       docker push frank15ortiz/testing:$GITHUB_SHA
  
  
