name: Docker CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag royal-docker:$GITHUB_SHA --tag royal-docker:latest

    - name: Push the Docker image
      run: docker push
  
  
