name: Docker CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}

    - name: Build & Push the Docker image
      run: |
       docker build . --file Dockerfile --tag testing:$GITHUB_SHA --tag testing:latest
       docker push ${{ secrets.DOCKER_USERNAME }}/testing:$GITHUB_SHA
  
  
